name: CI

on: [push, pull_request]

jobs:
  macOS:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.62.0
        override: true
        components: rustfmt
    - uses: actions/setup-go@v3
      with:
        go-version: 1.18.3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install Bazel
      run: brew install bazelisk
    - name: Install Buildifier
      run: go install github.com/bazelbuild/buildtools/buildifier@latest
    - name: Install commitlint
      run: npm install -g @commitlint/cli @commitlint/config-conventional
    - name: Install pre-commit
      run: brew install pre-commit
    - name: Lint Commit Messages
      run: commitlint --from origin/main --to HEAD
    - name: Lint
      run: pre-commit run -a
    - name: Build
      run: bazel build //...
